version: 0.2
os: linux

phases:
  install:
    commands:
      - sh test.sh
      - ./script/init.sh
      - ./script/eksctl_init.sh
  build:
    commands:
      - ./script/docker_build.sh
  post_build:
    command:
      - ./script/upload_to_ecr.sh
    finally:
      - echo 'Done'
