version: 0.2
os: linux

phases:
  install:
    commands:
      - sh script/init.sh
      - sh script/eksctl_init.sh
  build:
    commands:
      - sh script/docker_build.sh
  post_build:
    commands:
      - sh script/upload_to_ecr.sh
    finally:
      - echo 'Done'
