version: 0.2
os: linux

phases:
  install:
    commands:
      - ./script/init.sh
      - ./script/eksctl_init.sh
  build:
    commands:
      - ./script/docker_build.sh
  post_build:
    commands:
      - ./script/deploy_to_eks.sh
