apiVersion: apps/v1
kind: Deployment # kubernetes object type
metadata:
  name: eks-web # deployment name
spec:
  replicas: 3 # number of replicas
  selector:
    matchLabels:
      app: eks-web
  template:
    metadata:
      labels:
        app: eks-web # pod labels
    spec:
      containers:
      - name: eks-web # container name
        image: eks-web:latest
        imagePullPolicy: IfNotPresent # if exists, will not pull new image
        ports: # container and host port assignments
        - containerPort: 80
        - containerPort: 443